# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_powerguardian_powerpupil_powersensei_powertopicexpert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerguardian',
            name='assigned',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='powerpupil',
            name='assigned',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='powersensei',
            name='assigned',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='powertopicexpert',
            name='assigned',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
