# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_auto_20160131_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='pen_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
