# Generated by Django 2.2.3 on 2019-07-25 17:20

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('problembase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='problem.ProblemBase')),
                ('qtype', models.IntegerField(choices=[(0, 'Unassigned'), (1, 'Fill in the Blank'), (2, 'True or False'), (3, 'Multiple Choice'), (4, 'Problem Set'), (5, 'Short Answer'), (6, 'Multiple Answer'), (7, 'Word Problem')], default=0)),
                ('stem', jsonfield.fields.JSONField()),
                ('keys', jsonfield.fields.JSONField()),
            ],
            bases=('problem.problembase', models.Model),
        ),
        migrations.CreateModel(
            name='ReadingPassage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Spelling',
            fields=[
                ('reading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='readings.Reading')),
            ],
            bases=('readings.reading',),
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('reading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='readings.Reading')),
            ],
            bases=('readings.reading',),
        ),
        migrations.AddField(
            model_name='reading',
            name='passage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='readings.ReadingPassage'),
        ),
    ]
