# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 01:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0005_auto_20160207_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spelling',
            fields=[
                ('problembase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='problem.ProblemBase')),
                ('qtype', models.IntegerField(choices=[(0, 'Unassigned'), (1, 'Fill in the Blank'), (2, 'True or False'), (3, 'Multiple Choice'), (4, 'Problem Set'), (5, 'Short Answer'), (6, 'Multiple Answer')], default=0)),
                ('stem', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('keys', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('validation', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('explanation', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
            bases=('problem.problembase', models.Model),
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('problembase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='problem.ProblemBase')),
                ('qtype', models.IntegerField(choices=[(0, 'Unassigned'), (1, 'Fill in the Blank'), (2, 'True or False'), (3, 'Multiple Choice'), (4, 'Problem Set'), (5, 'Short Answer'), (6, 'Multiple Answer')], default=0)),
                ('stem', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('keys', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('validation', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('explanation', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
            bases=('problem.problembase', models.Model),
        ),
    ]
