# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 05:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spelling',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='spelling',
            name='keys',
        ),
        migrations.RemoveField(
            model_name='spelling',
            name='stem',
        ),
        migrations.RemoveField(
            model_name='spelling',
            name='validation',
        ),
        migrations.RemoveField(
            model_name='vocabulary',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='vocabulary',
            name='keys',
        ),
        migrations.RemoveField(
            model_name='vocabulary',
            name='stem',
        ),
        migrations.RemoveField(
            model_name='vocabulary',
            name='validation',
        ),
    ]
