# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0008_auto_20160226_2325'),
        ('readings', '0002_auto_20160226_0529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('problembase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='problem.ProblemBase')),
                ('qtype', models.IntegerField(choices=[(0, 'Unassigned'), (1, 'Fill in the Blank'), (2, 'True or False'), (3, 'Multiple Choice'), (4, 'Problem Set'), (5, 'Short Answer'), (6, 'Multiple Answer')], default=0)),
            ],
            bases=('problem.problembase', models.Model),
        ),
        migrations.RemoveField(
            model_name='spelling',
            name='problembase_ptr',
        ),
        migrations.RemoveField(
            model_name='spelling',
            name='qtype',
        ),
        migrations.RemoveField(
            model_name='vocabulary',
            name='problembase_ptr',
        ),
        migrations.RemoveField(
            model_name='vocabulary',
            name='qtype',
        ),
        migrations.AddField(
            model_name='spelling',
            name='reading_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='readings.Reading'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='reading_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='readings.Reading'),
            preserve_default=False,
        ),
    ]
