# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-21 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0003_auto_20160226_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='qtype',
            field=models.IntegerField(choices=[(0, 'Unassigned'), (1, 'Fill in the Blank'), (2, 'True or False'), (3, 'Multiple Choice'), (4, 'Problem Set'), (5, 'Short Answer'), (6, 'Multiple Answer'), (7, 'Word Problem')], default=0),
        ),
    ]
