# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-25 04:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0004_auto_20160721_0237'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingPassage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='reading',
            name='keys',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='reading',
            name='stem',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='reading',
            name='passage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='readings.ReadingPassage'),
        ),
    ]
