# Generated by Django 2.2.3 on 2019-07-25 17:19

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Math',
            fields=[
                ('problembase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='problem.ProblemBase')),
                ('qtype', models.IntegerField(choices=[(0, 'Unassigned'), (1, 'Fill in the Blank'), (2, 'True or False'), (3, 'Multiple Choice'), (4, 'Problem Set'), (5, 'Short Answer'), (6, 'Multiple Answer'), (7, 'Word Problem')], default=0)),
                ('content', tinymce.models.HTMLField()),
                ('stem', jsonfield.fields.JSONField()),
                ('keys', jsonfield.fields.JSONField()),
            ],
            bases=('problem.problembase', models.Model),
        ),
        migrations.CreateModel(
            name='Addition',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mathematics.math',),
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mathematics.math',),
        ),
        migrations.CreateModel(
            name='Fraction',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mathematics.math',),
        ),
        migrations.CreateModel(
            name='Multiplication',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mathematics.math',),
        ),
        migrations.CreateModel(
            name='Subtraction',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mathematics.math',),
        ),
    ]
