# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 19:47
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editor', '0004_editor_pen_name'),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Created'), (1, 'Defat'), (2, 'Published'), (3, 'Revised'), (4, 'Lock')], default=0)),
                ('qtype', models.IntegerField(choices=[(0, 'Unassigned'), (1, 'Fill in the Blank'), (2, 'True or False'), (3, 'Multiple Choice')], default=0)),
                ('stem', django.contrib.postgres.fields.jsonb.JSONField()),
                ('keys', django.contrib.postgres.fields.jsonb.JSONField()),
                ('validation', django.contrib.postgres.fields.jsonb.JSONField()),
                ('editors', models.ManyToManyField(to='editor.Editor')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
