# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 06:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraction',
            name='explanation',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fraction',
            name='qtype',
            field=models.IntegerField(choices=[(0, 'Unassigned'), (1, 'Fill in the Blank'), (2, 'True or False'), (3, 'Multiple Choice'), (4, 'Problem Set'), (5, 'Short Answer'), (6, 'Multiple Answer')], default=0),
        ),
    ]
