# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 02:21
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0002_auto_20170829_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='math',
            name='content',
            field=tinymce.models.HTMLField(default='<b>Test</b>'),
            preserve_default=False,
        ),
    ]
