# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 03:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0003_auto_20160203_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraction',
            name='explanation',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='fraction',
            name='keys',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='fraction',
            name='stem',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='fraction',
            name='validation',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
