# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0004_auto_20160203_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraction',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
