# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_auto_20160209_0317'),
        ('mathematics', '0005_auto_20160205_0525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fraction',
            name='editors',
        ),
        migrations.RemoveField(
            model_name='fraction',
            name='id',
        ),
        migrations.RemoveField(
            model_name='fraction',
            name='name',
        ),
        migrations.RemoveField(
            model_name='fraction',
            name='status',
        ),
        migrations.RemoveField(
            model_name='fraction',
            name='tags',
        ),
        migrations.AddField(
            model_name='fraction',
            name='problembase_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='problem.ProblemBase'),
            preserve_default=False,
        ),
    ]
