# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 05:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0006_auto_20160209_0318'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fraction',
            new_name='Math',
        ),
    ]
