# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0008_fraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addition',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('mathematics.math',),
        ),
    ]
