# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0009_addition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('mathematics.math',),
        ),
        migrations.CreateModel(
            name='Multiplication',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('mathematics.math',),
        ),
        migrations.CreateModel(
            name='Subtraction',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('mathematics.math',),
        ),
    ]
