# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-21 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('mathematics', '0010_division_multiplication_subtraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='math',
            name='topic',
            field=taggit.managers.TaggableManager(help_text='A comma separated list of valid topics this question covers', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Math Topics'),
        ),
        migrations.AlterField(
            model_name='math',
            name='qtype',
            field=models.IntegerField(choices=[(0, 'Unassigned'), (1, 'Fill in the Blank'), (2, 'True or False'), (3, 'Multiple Choice'), (4, 'Problem Set'), (5, 'Short Answer'), (6, 'Multiple Answer'), (7, 'Word Problem')], default=0),
        ),
    ]
