# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-21 02:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0011_auto_20160721_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='math',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='math',
            name='validation',
        ),
    ]
