# Generated by Django 2.2.3 on 2019-07-25 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(default=0.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pen_name', models.CharField(default='', max_length=100)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pen_name', models.CharField(default='', max_length=100)),
                ('teachers', models.ManyToManyField(to='classroom.Sensei')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamProblems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('status', models.IntegerField(choices=[(0, 'Created'), (1, 'Draft'), (2, 'Submitted'), (3, 'Lock')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('problems', models.ManyToManyField(blank=True, to='problem.ProblemInstance')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classroom.Sensei')),
            ],
        ),
        migrations.CreateModel(
            name='ExamAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', jsonfield.fields.JSONField()),
                ('results', jsonfield.fields.JSONField()),
                ('grade', models.FloatField(default=0.0)),
                ('status', models.IntegerField(choices=[(0, 'Created'), (1, 'Draft'), (2, 'Submitted'), (3, 'Lock')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classroom.ExamProblems')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classroom.Pupil')),
            ],
        ),
        migrations.CreateModel(
            name='ClassAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('assignments', models.ManyToManyField(to='classroom.Assignment')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classroom.Class')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classroom.ExamProblems')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(to='classroom.Pupil'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classroom.Sensei'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='answers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='classroom.ExamAnswers'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classroom.ExamProblems'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classroom.Pupil'),
        ),
    ]
