# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 03:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(default=0.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('assignments', models.ManyToManyField(to='classroom.Assignment')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Class')),
            ],
        ),
        migrations.CreateModel(
            name='ExamAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', django_mysql.models.JSONField(default=dict)),
                ('results', django_mysql.models.JSONField(default=dict)),
                ('grade', models.FloatField(default=0.0)),
                ('status', models.IntegerField(choices=[(0, b'Created'), (1, b'Draft'), (2, b'Submitted'), (3, b'Lock')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamProblems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=100)),
                ('status', models.IntegerField(choices=[(0, b'Created'), (1, b'Draft'), (2, b'Submitted'), (3, b'Lock')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('problems', models.ManyToManyField(blank=True, to='problem.ProblemInstance')),
            ],
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pen_name', models.CharField(default=b'', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sensei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pen_name', models.CharField(default=b'', max_length=100)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pupil',
            name='teachers',
            field=models.ManyToManyField(to='classroom.Sensei'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examproblems',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Sensei'),
        ),
        migrations.AddField(
            model_name='examanswers',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.ExamProblems'),
        ),
        migrations.AddField(
            model_name='examanswers',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Pupil'),
        ),
        migrations.AddField(
            model_name='classassignment',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.ExamProblems'),
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(to='classroom.Pupil'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Sensei'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='answers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.ExamAnswers'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.ExamProblems'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Pupil'),
        ),
    ]
