# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_auto_20160207_0450'),
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examanswers',
            name='answers',
            field=models.ManyToManyField(to='problem.AnswerInstance'),
        ),
        migrations.AddField(
            model_name='examproblems',
            name='problems',
            field=models.ManyToManyField(to='problem.ProblemInstance'),
        ),
    ]
