# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-21 02:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20160218_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examanswers',
            name='answers',
        ),
        migrations.AddField(
            model_name='examanswers',
            name='answers',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, verbose_name={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examanswers',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.ExamProblems'),
        ),
        migrations.AlterField(
            model_name='examanswers',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Pupil'),
        ),
    ]
