# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-21 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20160721_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='examproblems',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pupil',
            name='pen_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sensei',
            name='pen_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
