# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-23 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20160721_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='examanswers',
            name='grade',
            field=models.FloatField(default=0.0),
        ),
    ]
