# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-23 18:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_examanswers_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='examanswers',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 23, 18, 19, 4, 524337, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examanswers',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 23, 18, 19, 9, 636760, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examanswers',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Draft'), (2, 'Submitted'), (3, 'Lock')], default=0),
        ),
        migrations.AddField(
            model_name='examproblems',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 23, 18, 19, 16, 500342, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examproblems',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 23, 18, 19, 20, 556683, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examproblems',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Draft'), (2, 'Submitted'), (3, 'Lock')], default=0),
        ),
    ]
