# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-24 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_auto_20160723_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='teachers',
            field=models.ManyToManyField(to='classroom.Sensei'),
        ),
    ]
