# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-03 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_examanswers_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(default=0.0)),
                ('answers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.ExamAnswers')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.ExamProblems')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Pupil')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('students', models.ManyToManyField(to='classroom.Pupil')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Sensei')),
            ],
        ),
    ]
