# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-04 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_auto_20160904_0442'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('assignments', models.ManyToManyField(to='classroom.Assignment')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Class')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.ExamProblems')),
            ],
        ),
    ]
