# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-06 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_classassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='answers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.ExamAnswers'),
        ),
    ]
