# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-23 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0013_auto_20160906_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examproblems',
            name='problems',
            field=models.ManyToManyField(blank=True, to='problem.ProblemInstance'),
        ),
    ]
