---

- name: Ensure packages are installed
  apt: pkg={{ item }}
  with_items:
    - python-mysqldb
    - mysql-server

- name: Start the MySQL service
  service:
    name: mysql
    state: started
    enabled: true

- name: Create database user
  mysql_user: user={{ db_user }}
              password={{ db_password }}
              priv=*.*:ALL
              state=present

- name: Create database
  mysql_db: db={{ db_name }}
            state=present

#- name: Copy .my.cnf file with root password credentials
#  template: src=templates/my.conf.j2 dest=/etc/mysql/my.cnf owner=root mode=0600


- include: firewall.yml
