# Generated by Django 2.2.3 on 2019-07-25 17:19

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topic', '__first__'),
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(0, 'Created'), (1, 'Draft'), (2, 'Submitted'), (3, 'Reviewed'), (4, 'Published'), (5, 'Revised'), (6, 'Lock')], default=0)),
                ('domain', models.IntegerField(choices=[(0, 'Unknown'), (1000, 'Mathematic'), (1001, 'Addition'), (1002, 'Subtraction'), (1003, 'Multiplication'), (1004, 'Division'), (1005, 'Fraction'), (2000, 'Reading'), (2001, 'Spelling'), (2002, 'Vocabulary')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('editors', models.ManyToManyField(to='editor.Editor')),
                ('topics', models.ManyToManyField(default=None, to='topic.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerFillInTheBlank',
            fields=[
                ('answerinstance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='problem.AnswerInstance')),
                ('data', models.CharField(default='', max_length=150)),
            ],
            bases=('problem.answerinstance',),
        ),
        migrations.CreateModel(
            name='AnswerMultipleChoice',
            fields=[
                ('answerinstance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='problem.AnswerInstance')),
                ('data', models.IntegerField(default=-1)),
            ],
            bases=('problem.answerinstance',),
        ),
        migrations.CreateModel(
            name='AnswerShortAnswer',
            fields=[
                ('answerinstance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='problem.AnswerInstance')),
                ('data', models.CharField(default='', max_length=400)),
            ],
            bases=('problem.answerinstance',),
        ),
        migrations.CreateModel(
            name='AnswerTrueOrFalse',
            fields=[
                ('answerinstance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='problem.AnswerInstance')),
                ('data', models.BooleanField(default=None)),
            ],
            bases=('problem.answerinstance',),
        ),
        migrations.CreateModel(
            name='ProblemInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONField()),
                ('root', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='problem.ProblemBase')),
            ],
        ),
        migrations.AddField(
            model_name='answerinstance',
            name='problem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='problem.ProblemInstance'),
        ),
    ]
