# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionTypeBase',
        ),
    ]
