# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 02:21
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20170829_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problembase',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
