# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 04:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20160207_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='answermultiplechoice',
            name='id',
        ),
        migrations.RemoveField(
            model_name='answermultiplechoice',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='answershortanswer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='answershortanswer',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='answertrueorfalse',
            name='id',
        ),
        migrations.RemoveField(
            model_name='answertrueorfalse',
            name='problem',
        ),
        migrations.AlterField(
            model_name='answermultiplechoice',
            name='data',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='answershortanswer',
            name='data',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='answertrueorfalse',
            name='data',
            field=models.BooleanField(default=None),
        ),
        migrations.CreateModel(
            name='AnswerFillInTheBlank',
            fields=[
                ('answerinstance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='problem.AnswerInstance')),
                ('data', models.CharField(default='', max_length=150)),
            ],
            bases=('problem.answerinstance',),
        ),
        migrations.AddField(
            model_name='answerinstance',
            name='problem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='problem.ProblemInstance'),
        ),
        migrations.AddField(
            model_name='answermultiplechoice',
            name='answerinstance_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='problem.AnswerInstance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answershortanswer',
            name='answerinstance_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='problem.AnswerInstance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answertrueorfalse',
            name='answerinstance_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='problem.AnswerInstance'),
            preserve_default=False,
        ),
    ]
