# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('editor', '0004_editor_pen_name'),
        ('problem', '0004_auto_20160207_0450'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(0, 'Created'), (1, 'Default'), (2, 'Published'), (3, 'Revised'), (4, 'Lock')], default=0)),
                ('editors', models.ManyToManyField(to='editor.Editor')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.AddField(
            model_name='probleminstance',
            name='root',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.ProblemBase'),
            preserve_default=False,
        ),
    ]
