# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_auto_20160207_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problembase',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Draft'), (2, 'Published'), (3, 'Revised'), (4, 'Lock')], default=0),
        ),
        migrations.AlterField(
            model_name='probleminstance',
            name='root',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='problem.ProblemBase'),
        ),
    ]
