# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_auto_20160209_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='problembase',
            name='domain',
            field=models.IntegerField(default=0),
        ),
    ]
