# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0007_problembase_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problembase',
            name='domain',
            field=models.IntegerField(choices=[(1001, 'Addition'), (1002, 'Subtraction'), (1003, 'Multiplication'), (1004, 'Division'), (1005, 'Fraction')], default=0),
        ),
    ]
