# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-18 16:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0009_auto_20160227_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='problembase',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 18, 16, 21, 37, 873721, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problembase',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 18, 16, 21, 45, 691061, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
