# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-25 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0011_auto_20160704_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problembase',
            name='domain',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1000, 'Mathematic'), (1001, 'Addition'), (1002, 'Subtraction'), (1003, 'Multiplication'), (1004, 'Division'), (1005, 'Fraction'), (2000, 'Reading'), (2001, 'Spelling'), (2002, 'Vocabulary')], default=0),
        ),
    ]
