# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-25 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
        ('problem', '0012_auto_20160725_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='problembase',
            name='topics',
            field=models.ManyToManyField(to='topic.Topic'),
        ),
    ]
