# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-25 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0013_problembase_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problembase',
            name='topics',
            field=models.ManyToManyField(default=None, to='topic.Topic'),
        ),
    ]
