DOMAIN_UNKNOWN = 0

DOMAIN_MATH = 1000

# DEPRECATE
DOMAIN_ADDITION = 1001
DOMAIN_SUBTRACTION = 1002
DOMAIN_MULTIPLICATION = 1003
DOMAIN_DIVISION = 1004
DOMAIN_FRACTIONS = 1005

DOMAIN_READING = 2000
DOMAIN_SPELLING = 2001
DOMAIN_VOCABULARY = 2002

DOMAIN_WRITING = 3000

DOMAIN_CHOICES = [
    (DOMAIN_UNKNOWN, 'Unknown'),

    (DOMAIN_MATH, 'Mathematic'),
    (DOMAIN_ADDITION, 'Addition'),
    (DOMAIN_SUBTRACTION, 'Subtraction'),
    (DOMAIN_MULTIPLICATION, 'Multiplication'),
    (DOMAIN_DIVISION, 'Division'),
    (DOMAIN_FRACTIONS, 'Fraction'),

    (DOMAIN_READING, 'Reading'),
    (DOMAIN_SPELLING, 'Spelling'),
    (DOMAIN_VOCABULARY, 'Vocabulary')
]

DOMAIN_DICT = {}
for id, value in DOMAIN_CHOICES:
    DOMAIN_DICT[id] = value
