
- name: Ensure test database is created
  sudo_user: postgres
  postgresql_db: name={{ test_db_name }}
                 encoding='UTF-8'
                 lc_collate='en_US.UTF-8'
                 lc_ctype='en_US.UTF-8'
                 template='template0'
                 state=present

- name: Ensure test user has access to the database
  sudo_user: postgres
  postgresql_user: db={{ test_db_name }}
                   name={{ test_db_user }}
                   password={{ test_db_password }}
                   priv=ALL
                   state=present

- name: Ensure user does not have unnecessary privileges
  sudo_user: postgres
  postgresql_user: name={{ test_db_user }}
                   role_attr_flags=SUPERUSER,CREATEDB
                   state=present
